// Every project on the Work page and on its own page. Edit the text here.
const GH = 'https://github.com/Ifran08'

export const PROJECTS = [
  {
    slug: 'copper-clove',
    title: 'Copper & Clove',
    card: 'A five page restaurant site with a reservation form that really works. Bookings land in a PostgreSQL database and a confirmation email goes out.',
    hand: 'yes, the email really sends',
    stack: 'JavaScript, Express, Supabase, Resend',
    cardLink: ['Open the live site', 'https://clove-fawn-ten.vercel.app/'],
    lead: 'A restaurant website for a modern Indian kitchen concept, with a reservation form that really works.',
    idea: 'I wanted a project that shows more than a pretty page. Copper & Clove is a made up restaurant, but everything a real one needs is working: a menu, a story, and a booking form that saves reservations and sends an email.',
    built: [
      ['Pages', 'Five pages: Home, Menu, Reservations, Our Story and Contact.'],
      ['Navigation', 'A full screen hamburger menu that opens over the page.'],
      ['Reservations', 'The form sends each booking to an Express API, which saves it in a PostgreSQL database on Supabase.'],
      ['Email', 'An email goes out through Resend when a booking comes in.'],
      ['Launch', 'Deployed on Vercel, so anyone can open it.'],
    ],
    tags: ['HTML', 'CSS', 'JavaScript', 'Express', 'Supabase', 'PostgreSQL', 'Resend', 'Vercel'],
    links: [['Open the live site', 'https://clove-fawn-ten.vercel.app/']],
  },
  {
    slug: 'codash',
    title: 'CODASH',
    card: 'The multi page website for my own studio. The booking form calls an Express API on Render that checks the input, blocks spam and stores each booking.',
    stack: 'JavaScript, Express, PostgreSQL, Render',
    cardLink: ['Open the live site', 'http://www.codash.co.in'],
    lead: 'The website for my own web studio, made to bring in clients.',
    idea: 'CODASH is the studio I run. The site shows what we do and lets a visitor book a call or send a project inquiry.',
    built: [
      ['Pages', 'A multi page site written in plain HTML, CSS and JavaScript.'],
      ['Look', "Playful, colorful and energetic, using the studio's own cream and red colors with animation."],
      ['Booking form', 'The form on the contact page calls an Express API hosted on Render.'],
      ['Safety', 'The API checks the input, limits repeated requests and blocks spam before saving anything.'],
      ['Storage', 'Each booking is saved in a Supabase PostgreSQL database, and the studio gets an email through Resend.'],
    ],
    tags: ['HTML', 'CSS', 'JavaScript', 'Express', 'PostgreSQL', 'Supabase', 'Render', 'Resend'],
    links: [['Open the live site', 'http://www.codash.co.in'], ['Read the code', GH + '/CODASH-']],
  },
  {
    slug: 'particle',
    title: 'Particle agency',
    card: 'A Wix site rebuilt as hand written code. I fixed the Vercel deployment, repaired CSS paths and variables across 15 pages, and added a custom cursor and scroll animations.',
    status: 'UNDER-DEVELOPMENT',
    stack: 'Vanilla JS, CSS animation, Vercel',
    lead: 'An agency website that started on Wix and is being rebuilt as hand written code.',
    idea: 'The original site was made in Wix. I am rebuilding it with plain HTML, CSS and JavaScript so every part of it can be controlled and hosted anywhere.',
    built: [
      ['Rebuild', 'Turned the Wix pages into hand written code, around fifteen HTML pages.'],
      ['Fixes', 'Fixed the Vercel deployment, repaired broken CSS paths and added CSS variables that were missing across those pages.'],
      ['Motion', 'Added a custom cursor and scroll animations, inspired by patterns I studied on top agency sites.'],
      ['Status', 'Still under development, so there is no live link yet.'],
    ],
    tags: ['Vanilla JS', 'CSS animation', 'Vercel'],
    links: [],
  },
  {
    slug: 'biker-cafe',
    title: "Biker's Brewing Café",
    card: 'A responsive website for a café brand, built in HTML and CSS.',
    status: 'UNDER-DEVELOPMENT',
    stack: 'HTML, CSS',
    lead: 'A responsive website for a café brand.',
    idea: 'A simple website for a café brand, made to look good on any screen size.',
    built: [
      ['Layout', 'Adapts from phone to desktop.'],
      ['Stack', 'Built with HTML and CSS.'],
      ['Status', 'Still under development, so there is no live link yet.'],
    ],
    tags: ['HTML', 'CSS'],
    links: [],
  },
  {
    slug: 'react-games',
    title: 'React board games',
    card: 'Tic tac toe and chess, both built in React using components, props and state. Now I am teaching the chess bot to think, so it can be your opponent.',
    status: 'NEURAL CHESS LOADING',
    stack: 'React, useState',
    cardLink: ['Play tic tac toe', 'https://tic-tac-toe-gq7s.vercel.app/'],
    lead: 'Tic tac toe and chess, built with React.',
    idea: 'I built these to learn React properly: components, props and state. Tic tac toe came first, and chess followed in the same project.',
    built: [
      ['Tic tac toe', 'Live and playable, built with components, props and state.'],
      ['Chess', 'Built, and still being developed.'],
      ['Next step', 'An AI opponent, so you can play human vs AI. I am exploring the neural world of chess to give it a brain.'],
    ],
    tags: ['React', 'useState', 'Vercel'],
    links: [['Play tic tac toe', 'https://tic-tac-toe-gq7s.vercel.app/'], ['See my GitHub', GH]],
  },
  {
    slug: 'experiments',
    title: 'Reflex test and emotion journal',
    card: 'Two quick experiments in pure JavaScript: a reaction speed game and a journal where you log your feelings as glyphs.',
    status: 'WORK-IN-PROGRESS',
    stack: 'JavaScript, DOM',
    lead: 'Two quick experiments in pure JavaScript.',
    idea: 'Small builds like these are where I try ideas without a client or a deadline.',
    built: [
      ['Reflex test', 'A game that measures how fast you react.'],
      ['Emotion journal', 'A journal where you log your feelings as glyphs instead of words.'],
      ['Status', 'Still a work in progress, so there is no live link yet.'],
    ],
    tags: ['JavaScript', 'DOM'],
    links: [],
  },
]
